export const CARD_NUMBER_ACTION = "CARD_NUMBER_ACTION";
export const MONTH_ACTION = "MONTH_ACTION";
export const YEAR_ACTION = "YEAR_ACTION";
export const CVV_ACTION = "CVV_ACTION";
export const ROTATE_ACTION = "ROTATE_ACTION";
export const CARD_HOLDER_NAME_ACTION = "CARD_HOLDER_NAME_ACTION";